<?php

defined('_JEXEC') or die;

use Joomla\CMS\
{
	Factory,
	Language\Text,
	Router\Route,
	MVC\Controller\FormController,
};

class TranslatorControllerFile extends FormController
{

	/**
	 * @param string $name
	 * @param string $prefix
	 * @param array  $config
	 *
	 * @return JModelLegacy | TranslatorModelFile
	 *
	 * @since version
	 */
	public function getModel($name = 'File', $prefix = 'TranslatorModel', $config = array('ignore_request' => true))
	{
		return parent::getModel($name, $prefix, $config); // TODO: Change the autogenerated stub
	}

	public function cancel($key = null)
	{
		if ($this->checkToken() === false)
		{
			die('Error Token');
		}
		$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_list, false));

		return true;
	}


	public function save($key = null, $urlVar = null)
	{
		if ($this->checkToken() === false)
		{
			die('Error Token');
		}

		$app   = Factory::getApplication();
		$model = $this->getModel();
		$data  = $this->input->post->get('jform', array(), 'array');
		$form  = $model->getForm($data, false);
		if (!$form)
		{
			$app->enqueueMessage($model->getError(), 'error');

			return false;
		}
		$validData = $model->validate($form, $data);
		if ($validData === false)
		{
			// Get the validation messages.
			$errors = $model->getErrors();

			// Push up to three validation messages out to the user.
			for ($i = 0, $n = count($errors); $i < $n && $i < 3; $i++)
			{
				if ($errors[$i] instanceof Exception)
				{
					$app->enqueueMessage($errors[$i]->getMessage(), 'warning');
				}
				else
				{
					$app->enqueueMessage($errors[$i], 'warning');
				}
			}
			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_item . '&layout=edit', false));

			return false;
		}

		try
		{
			$file = $model->save($validData);

			$exists = $model->getState('file_exists', false);

			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=constants&file=' . $file, false), Text::_(($exists ? 'COM_TRANSLATOR_FILE_ALREADY_EXIST' : 'COM_TRANSLATOR_FILE_ADDED')));
		}
		catch (Exception $e)
		{
			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_list, false), $e->getMessage(), 'error');

			return false;
		}

		return true;

	}

}