<?php

defined('_JEXEC') or die;

use Joomla\CMS\
{
	Factory,
	Language\Text,
	Router\Route,
	MVC\Controller\FormController,
	Session\Session
};

class TranslatorControllerFile extends FormController
{

	/**
	 * @param string $name
	 * @param string $prefix
	 * @param array  $config
	 *
	 * @return JModelLegacy | TranslatorModelFile
	 *
	 * @since version
	 */
	public function getModel($name = 'File', $prefix = 'TranslatorModel', $config = array('ignore_request' => true))
	{
		return parent::getModel($name, $prefix, $config); // TODO: Change the autogenerated stub
	}

	public function cancel($key = null)
	{
		$this->checkToken('post', false) or die('Error Token');
		$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_list, false));

		return true;
	}


	public function save($key = null, $urlVar = null)
	{
		$this->checkToken('post', false) or die('Error Token');

		$app   = Factory::getApplication();
		$model = $this->getModel();
		$data  = $this->input->post->get('jform', array(), 'array');
		$form  = $model->getForm($data, false);
		if (!$form)
		{
			$app->enqueueMessage($model->getError(), 'error');

			return false;
		}
		$validData = $model->validate($form, $data);
		if ($validData === false)
		{
			// Get the validation messages.
			$errors = $model->getErrors();

			// Push up to three validation messages out to the user.
			for ($i = 0, $n = count($errors); $i < $n && $i < 3; $i++)
			{
				if ($errors[$i] instanceof Exception)
				{
					$app->enqueueMessage($errors[$i]->getMessage(), 'warning');
				}
				else
				{
					$app->enqueueMessage($errors[$i], 'warning');
				}
			}
			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_item . '&layout=edit', false));

			return false;
		}

		try
		{
			$file = $model->save($validData);

			$exists = $model->getState('file_exists', false);

			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=constants&file=' . $file, false), Text::_(($exists ? 'COM_TRANSLATOR_FILE_ALREADY_EXIST' : 'COM_TRANSLATOR_FILE_ADDED')));
		}
		catch (Exception $e)
		{
			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_list, false), $e->getMessage(), 'error');

			return false;
		}

		return true;

	}


	public function reSave()
	{
		$this->checkToken('post', false) or die('Error Token');
		$cid   = $this->input->get('cid', [], 'array');
		$model = $this->getModel();
		$model->reSave($cid);
		$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_list, false))->redirect();
	}

	public function create()
	{
		$this->checkToken('get', false) or die('Error Token');
		$file = $this->input->get->get('file', null, 'raw');
		try
		{
			if (empty($file))
			{
				throw new Exception(Text::_('COM_TRANSLATOR_MISSING_FILE'));
			}

			$fileExpl = explode(':', $file);

			if (!empty($fileExpl[1]))
			{
				$filename = $fileExpl[1];
			}
			else
			{
				throw new Exception(Text::_('COM_TRANSLATOR_FILENAME_EMPTY'));
			}

			if($fileExpl[0] === 'site')
			{
				$client = 1;
			}
			else
			{
				$client = 0;
			}

			$data = [];

			$filename = str_replace('.sys', '', $filename);

			if($filename === $fileExpl[1])
			{
				$data['sys'] = 0;
			}
			else
			{
				$data['sys'] = 1;
			}

			$filename = str_replace('.ini', '', $filename);

			$fileExpl = explode('.', $filename);

			if (empty($fileExpl[1]))
			{
				throw new Exception(Text::_('COM_TRANSLATOR_CREATE_FILE_EXPANSION_ONLY'));
			}

			$data['language'] = $fileExpl[0].$client;
			$data['extension'] = $fileExpl[1];

			$this->input->post->set('jform', $data);
			$this->input->post->set(Session::getFormToken(), '1');

			$this->save();
		}
		catch (Exception $e)
		{
			$this->setRedirect(Route::_('index.php?option=' . $this->option . '&view=' . $this->view_list, false), $e->getMessage(), 'error')->redirect();
		}
	}

}